libname mylib  '/scratch/cbs/cst';

PROC SQL;
CREATE TABLE mylib.fisd_issue AS
SELECT ISSUE_ID , ISSUER_ID, COMPLETE_CUSIP , PROSPECTUS_ISSUER_NAME , ISSUER_CUSIP , ISSUE_CUSIP , ISSUE_NAME , MATURITY, OFFERING_DATE, OFFERING_AMT, AMOUNT_OUTSTANDING,
DAY_COUNT_BASIS, DEFAULTED, coupon_type, coupon, interest_frequency, bond_type, principal_amt, dated_date, first_interest_date, last_interest_date,
SECURITY_LEVEL , SECURITY_PLEDGE , ENHANCEMENT , CONVERTIBLE , MTN , ASSET_BACKED , YANKEE , CANADIAN , OID , FOREIGN_CURRENCY , SLOB , ISSUE_OFFERED_GLOBAL,
SETTLEMENT_TYPE , GROSS_SPREAD , SELLING_CONCESSION , REALLOWANCE , COMP_NEG_EXCH_DEAL , RULE_415_REG , SEC_REG_TYPE1 , SEC_REG_TYPE2 , RULE_144A, TREASURY_SPREAD
FROM FISD.FISD_MERGEDISSUE;
RUN;
QUIT;

PROC SQL;
CREATE TABLE mylib.fisd_amt_out AS
SELECT A.ISSUE_ID , A.EFFECTIVE_DATE , A.AMOUNT_OUTSTANDING,
B.ISSUE_ID, B.COMPLETE_CUSIP
FROM FISD.FISD_AMOUNT_OUTSTANDING as A
LEFT JOIN FISD.FISD_MERGEDISSUE AS B
ON A.ISSUE_ID=B.ISSUE_ID;
RUN;
QUIT;

PROC SQL;
CREATE TABLE mylib.fisd_amt_out_hist AS
SELECT A.ISSUE_ID , A.EFFECTIVE_DATE , A.AMOUNT_OUTSTANDING,
B.ISSUE_ID, B.COMPLETE_CUSIP
FROM FISD.FISD_AMT_OUT_HIST as A
LEFT JOIN FISD.FISD_MERGEDISSUE AS B
ON A.ISSUE_ID=B.ISSUE_ID;
RUN;
QUIT;

PROC SQL;
CREATE TABLE mylib.bondcrsp_link AS
SELECT CUSIP , PERMNO , PERMCO , trace_startdt , trace_enddt , crsp_startdt , crsp_enddt , link_startdt , link_enddt FROM WRDSAPPS.BONDCRSP_LINK;
RUN;
QUIT;

PROC SQL;
CREATE TABLE mylib.fisd_defaults AS
SELECT DEFAULT_DATE , ISSUE_ID , DEFAULT_TYPE , REINSTATED , REINSTATED_DATE , NOTE FROM FISD.FISD_ISSUE_DEFAULT;
RUN;
QUIT;

PROC SQL;
CREATE TABLE mylib.fisd_ratings AS
SELECT * FROM FISD.FISD_RATINGS;
RUN;
QUIT;


*** Selects the FAMA TREASURY dataset;
proc sql; 
create table temp01
as select distinct a.*
from  CRSPA.TFZ_MTH_BP a; 
quit;

data mylib.fama_treasury (drop = mcaldt);
 set temp01;
 where kytreasnox = 2000039;
 date = mcaldt;

 format date date9.;
run;
